### PR TITLE
Check guest user permissions in usePermissions hook

### PR DESCRIPTION
**Pull request by samshara**
## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

### CODE REVIEW

**Review by tnagorra — COMMENTED** [review]
Don't we also need to remove checks for guest user in other places?

**Comment by samshara** [comment]
> Don't we also need to remove checks for guest user in other places?

@tnagorra here we have multiple places where we need to explicitly pass the Guest User Permissions.

For example,

```tsx
const newThreeWProject = customWrapRoute({
    parent: rootLayout,
    path: 'three-w/projects/new',
    component: {
        render: () => import('#views/ThreeWProjectForm'),
        props: {},
    },
    wrapperComponent: Auth,
    context: {
        title: 'New 3W Project',
        visibility: 'is-authenticated',
        permissions: ({ isGuestUser }) => !isGuestUser,
    },
});
````

**Comment by tnagorra** [comment]
@samshara We can explicitly pass them where needed but the change we introduced should remove most of the scenarios where we check for `isGuestUser`

**Comment by tnagorra** [comment]
@samshara We can explicitly pass them where needed but the change we introduced should remove most of the scenarios where we check for `isGuestUser`

Example:

```typescript
// app/src/views/CountryNsOverviewStrategicPriorities/index.tsx|50 col 14| || (!isGuestUser && isCountryPerAdmin(Number(countryId)))
const isPerAdmin = isSuperUser
    || (!isGuestUser && isCountryPerAdmin(Number(countryId)))
    || (!isGuestUser && isRegionPerAdmin(regionId));
```

**Review by tnagorra — APPROVED** [review]

**Pull request merged**
