### PR TITLE
Feature/dref import template improvements

### PR DESCRIPTION
**Pull request by tnagorra**
## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/1431
- https://github.com/IFRCGo/go-web-app/issues/1444

## Issues
- The data validation is not working on Google Sheets.

## Changes
- Add "hiddenLabel" for list types to hide labels
- Update labels and descriptions on the template export
  - Includes description for dynamic content
- Update styling of the export
    - Headers and description
- Add support for rich text on label and description
- Hide options sheet
- Rename 'headingType' to 'rowType'
- Append 4 new lines on text area to set initial height but also expand
  on content
- Update the layout of the first sheet.
- Update the error message when importing fails.

### Template Documents

- Template shared by IFRC: [20241022_DREF.import_v2_KJM.xlsx](https://github.com/user-attachments/files/17537056/20241022_DREF.import_v2_KJM.xlsx)
- ~Generated template: [DREF_Application_Response_import_template_25_10_2024,_16_08_46.xlsx](https://github.com/user-attachments/files/17537058/DREF_Application_Response_import_template_25_10_2024._16_08_46.xlsx)~
- ~Generated template: [DREF_Application_Response_import_template_28_10_2024,_15_09_23.xlsx](https://github.com/user-attachments/files/17540306/DREF_Application_Response_import_template_28_10_2024._15_09_23.xlsx)~
- ~Generated template: [DREF_Application_Response_import_template_29_10_2024,_16_42_36.xlsx](https://github.com/user-attachments/files/17555808/DREF_Application_Response_import_template_29_10_2024._16_42_36.xlsx)~
- Generated template: [DREF_Application_Response_import_template_30_10_2024,_16_45_09.xlsx](https://github.com/user-attachments/files/17571045/DREF_Application_Response_import_template_30_10_2024._16_45_09.xlsx)

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

### Operation Overview

1. Do we delete the "Essential Information" header?

### Event Detail

1. We cannot group the cells so the description will be repeated for
    - Did it affect the same population groups?
    - Did the National Society respond?
    - Did the National Society request funding from DREF for that event(s)?
    - If yes, please specify which operations
2. Do we delete the "If you have answered yes to all questions above, justify why the use of DREF for a recurrent event, or how this event should not be considered recurrent" field?
3. Do we rename the label "Date of the Event / Date when the trigger was met" to "Date of the Event"?
4. The description for "Date of the Event" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY"
5. We have added bold style to "Comparative Analysis". Is that correct?
6. Description has been removed from "Source Information" header. Is that correct?
7. The description on "Source Information" "Link" will be visible on all repetations. Is that correct?
7. The description of "Source Information" "Title" and "Link" cannot be grouped.
8. Header of "Source Information" items is "Red" instead of "Blue"

### Actions Needs

1. The description for "If yes, start date of National Society actions" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY"
2. "National Society Actions" has been hidden to make it consistent with "Planned Interventions" section. Is that correct?
3. Description has been removed from "National Society Actions" header. Is that correct?
4. We do not have support for adding variable value on "National Society Actions" items "Description"
5. Do we need to left align the label for "National Society Actions" items "Description"
6. Do we rename the label "ICRC" to "Descrption"?
7. Do we delete the "List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?" field?
8. We do not have support for adding variable value on "Needs Identified" items "Description"
9. Do we need to left align the label for "Needs Identified" items "Description"

### Operations

1. Do we need to left align the label for "Targeted Population: Women"
2. Do we need to left align the label for "Targeted Population: Men"
3. Do we need to left align the label for "Targeted Population: Girls (under 18)"
4. Do we need to left align the label for "Targeted Population: Boys (under 18)"
5. Do we need to left align the label for "Targeted Population: Total"
6. Do we need to left align the label for "Estimated Percentage: People with Disability"
7. Do we need to left align the label for "Estimated Percentage: Urban"
8. Do we need to left align the label for "Estimated Percentage: Rural"
9. Do we need to left align the label for "Estimated number of People on the move (if any)"
10. Do we need to left align the label for "Risk and security considerations" item's "Risk"
11. Do we need to left align the label for "Risk and security considerations" item's "Mitigation actions"
12. Do we need to left align the label for "Requested Amount in CHF"
13. The description will be repeated for "Planned Interventions" item's "Budget"
14. The description will be repeated for "Planned Interventions" item's "Person Targeted"
15. Do we need to left align the label for "Planned Interventions" item's "Budget"
16. Do we need to left align the label for "Planned Interventions" item's "Person Targeted"
17. Do we need to left align the label for "Planned Interventions" item's "List of Activities"
18. The description will be repeated for "Indicators" item's "Title"
19. The description will be repeated for "Indicators" item's "Target"
20. Do we need to left align the label for "Indicators" item's "Title"
21. Do we need to left align the label for "Indicators" item's "Target"

### Timeframe and Contacts

1. The description for "Date of the Event" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY"

### CODE REVIEW

**Comment by marcovvu1** [comment]
**ANSWERS** @udaynwa @anamariaescobar @tovari 
## Questions

### Operation Overview

1. Do we delete the "Essential Information" header? - YES THAT IS CORRECT
 
### Event Detail
1. We cannot group the cells so the description will be repeated for - THAT IS FINE

    - Did it affect the same population groups?

    - Did the National Society respond?

    - Did the National Society request funding from DREF for that event(s)?

    - If yes, please specify which operations

2. Do we delete the "If you have answered yes to all questions above, justify why the use of DREF for a recurrent event, or how this event should not be considered recurrent" field? - NO, SHOULD REMIND.

3. Do we rename the label "Date of the Event / Date when the trigger was met" to "Date of the Event"? - NO, TO KEEP AS "Date of the Event / Date when the trigger was met"

4. The description for "Date of the Event" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY" - IFRC DESING GUIDELINES REQUIRE US TO KEEP DATES AS DD/MM/YYYY FOR ALL DOCUMENTS

5. We have added bold style to "Comparative Analysis". Is that correct? - YES

6. Description has been removed from "Source Information" header. Is that correct? YES

7. The description on "Source Information" "Link" will be visible on all repetations. Is that correct? YES BETTER TO SHOW IN ALL

7. The description of "Source Information" "Title" and "Link" cannot be grouped. - LETS KEEP IT FOR THE "Link" FIELD ONLY

8. Header of "Source Information" items is "Red" instead of "Blue" - LETS KEEP IT BLUE



 ### Actions Needs



1. The description for "If yes, start date of National Society actions" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY" - SEE ABOVE, LETS KEEP IT AS SUCH

2. "National Society Actions" has been hidden to make it consistent with "Planned Interventions" section. Is that correct? - CORRECT

3. Description has been removed from "National Society Actions" header. Is that correct? - CORRECT

4. We do not have support for adding variable value on "National Society Actions" items "Description" - DO NOT UNDERSTAND THIS ONE

5. Do we need to left align the label for "National Society Actions" items "Description" - LEAVE AS IN VERSION SHARED BY YOU

6. Do we rename the label "ICRC" to "Descrption"? -YES, LEAVING THE HEADING "ICRC Actions Related to the Current Event"

7. Do we delete the "List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?" field? - YES, repeats with the above "Are there any Major Coordination Mechanism in place?" THIS IS ACTUALLY GUIDANCE FOR THAT FIELD, AND NOT A FIELD IN ITSELF

8. We do not have support for adding variable value on "Needs Identified" items "Description" - DO NOT UNDERSTAND

9. Do we need to left align the label for "Needs Identified" items "Description" - NO, LEAVE AS CURRENT



### Operations



1. Do we need to left align the label for "Targeted Population: Women" NO, LEAVE AS CURRENT FOR ALL

2. Do we need to left align the label for "Targeted Population: Men"

3. Do we need to left align the label for "Targeted Population: Girls (under 18)"

4. Do we need to left align the label for "Targeted Population: Boys (under 18)"

5. Do we need to left align the label for "Targeted Population: Total"

6. Do we need to left align the label for "Estimated Percentage: People with Disability"

7. Do we need to left align the label for "Estimated Percentage: Urban"

8. Do we need to left align the label for "Estimated Percentage: Rural"

9. Do we need to left align the label for "Estimated number of People on the move (if any)"

10. Do we need to left align the label for "Risk and security considerations" item's "Risk"

11. Do we need to left align the label for "Risk and security considerations" item's "Mitigation actions"

12. Do we need to left align the label for "Requested Amount in CHF"

13. The description will be repeated for "Planned Interventions" item's "Budget"

14. The description will be repeated for "Planned Interventions" item's "Person Targeted"

15. Do we need to left align the label for "Planned Interventions" item's "Budget"

16. Do we need to left align the label for "Planned Interventions" item's "Person Targeted"

17. Do we need to left align the label for "Planned Interventions" item's "List of Activities"

18. The description will be repeated for "Indicators" item's "Title"

19. The description will be repeated for "Indicators" item's "Target"

20. Do we need to left align the label for "Indicators" item's "Title"

21. Do we need to left align the label for "Indicators" item's "Target"



 ### Timeframe and Contacts



1. The description for "Date of the Event" might not be the best choice. "DD/MM/YYYY" can be confusing with "MM/DD/YYYY" - LEAVE DD/MM/YYYY

**Review by frozenhelium — APPROVED** [review]

**Comment by udaynwa** [comment]
Thank you for the answers, @marcovvu1 . They were implemented and pushed to Staging in the go-web-app v7.6.2 Staging deployment yesterday. 

However, we would like to note a few points: 

## Missing / to be implemented 
1. Description/guideline missing for Operations > Requested Amount in CHF. Description to be added: `General funding requested to fund the interventions.`
2. DREF Import Template> Estimated number of people on the move should be Number in the description instead of Percentage
unnamed

_(We will implement and push these 2 in the next Prod release)_

## Questions
1. In the Event Details tab, the following radio button question should appear only if the previous question was answered with "Yes." Each radio button question should have a unique description that directly references the preceding question, rather than repeating the same description across all radio button options.
For example, the descriptions could be as follows:
Indicate only if there was a similar event affecting the same area in the last 3 years. Otherwise, leave the box empty.
Indicate only if it affected the same population groups. Otherwise, leave the box empty.
Indicate only if the national society responded. Otherwise, leave the box empty.
Indicate only if the national society requested funding from DREF for that event. Otherwise, leave the box empty.
unnamed (3)
2. In the Actions/Needs tab, when clicked on ‘Yes’ for the ‘Are there major coordination mechanisms in place?’, the DREF form displays a description box which is missing on the DREF import template.
unnamed (4)

cc @tnagorra @shraeyaa

**Comment by udaynwa** [comment]
**Update**

@marcovvu1 , the Missing / to-be-implemented ones have been implemented and pushed to Staging with go-web-app v7.6.3 just now. 

cc @tnagorra

**Comment by marcovvu1** [comment]
Thanks @udaynwa, on your two questions. 

Agree with the proposed guidance for the questions that cascade

On the second point, yes indeed, that long text field should be available in the import template. 

Cc @tovari @anamariaescobar

**Pull request merged**
