### PR TITLE
[Hotfix 4]: Replace the from-communication-copied text of CoS Health header

### PR DESCRIPTION
**Pull request by szabozoltan69**
Refers to a correspondence with Surge team, where it was flagged that the Communications and Health has the same intro text.

### CODE REVIEW

**Review by samshara — APPROVED** [review]

**Review by samshara — DISMISSED** [review]
@szabozoltan69 the PR needs to be sent to the `hotfix/cos-health-updates` branch as the base branch instead of develop.

**Comment by samshara** [comment]
@szabozoltan69, some commits here are not relevant to the hotfix. Please cherry-pick only the necessary commits for the hotfix. Based on the review, it seems we only need this commit: [aafa45e](https://github.com/IFRCGo/go-web-app/pull/1472/commits/aafa45e99927a5115dc0b9f030e90562a9b39141). Thanks.

**Comment by samshara** [comment]
@szabozoltan69 I’ve cherry-picked your commit. Instead of merging it now, we’ll include it in an upcoming hotfix deployment.

**Review by tnagorra — APPROVED** [review]

**Comment by samshara** [comment]
included in https://github.com/IFRCGo/go-web-app/pull/1480

**Pull request closed without merging**
